### ISSUE TITLE
Google Play Protect recognizes the app as harmful

### ISSUE THREAD

**Issue by nvzeppelin** [aloussase/alexandria-app#22]
When updating from v0.2.0 to latest on F-Droid, I got a popup stating that the app may be harmful

![Screenshot_20240326_224331](https://github.com/aloussase/alexandria-app/assets/47154656/40d1c36b-33d1-48f9-9357-3289ac18fcbe)

**Comment by aloussase** [comment]
I don't know why this may be honestly.

**Comment by Delorean12DMC** [comment]
It's possible the app gets recognized as harmful because it relies on an external api to convert the books into another format. This behavior is also found in harmful software, where files get stolen from the user. But there is nothing to worry about in that case, because the app just relies on said api to convert the books. So it just uploads the downloaded file to an external service to convert it into a different file format and then downloads the converted file from that service. That is not harmful, but google still thinks that it is malicious. At the moment, there is no way around it.
